// src/components/shared/Navbar.svelte
<script lang="ts">
import { onMount } from 'svelte';
import ThemeToggle from './ThemeToggle.svelte';

const { pathname = '/' } = $props();

let active = $state('home');
let menuOpen = $state(false);

const navItems = [
  { label: 'Home', section: 'home', homepageOnly: true },
  { label: 'Services', section: 'services' },
  { label: 'About', section: 'about' },
  { label: 'Projects', section: 'projects' },
  { label: 'Blog', route: '/blog' },
  { label: 'Contact', section: 'contact', cta: true },
];

const onHome = pathname === '/';

function handleSectionNav(e: MouseEvent, id: string) {
  if (!onHome) return;
  e.preventDefault();
  const el = document.getElementById(id);
  if (el) {
    const y = el.getBoundingClientRect().top + window.scrollY - 80;
    window.scrollTo({ top: y, behavior: 'smooth' });
    menuOpen = false;
  }
}

onMount(() => {
  if (onHome) {
    const opts = {
      rootMargin: '-20% 0px -60% 0px',
      threshold: [0, 0.1, 0.5, 1],
    };

    const observer = new IntersectionObserver((entries) => {
      const sorted = entries
        .filter((e) => e.isIntersecting)
        .sort((a, b) => b.intersectionRatio - a.intersectionRatio);

      if (sorted.length > 0) {
        const id = sorted[0].target.getAttribute('id');
        if (id) active = id;
      }

      const contactSection = document.getElementById('contact');
      if (contactSection) {
        const rect = contactSection.getBoundingClientRect();
        const windowHeight = window.innerHeight;
        const atBottom =
          rect.top < windowHeight &&
          window.scrollY + windowHeight >= document.body.scrollHeight - 50;
        if (atBottom) active = 'contact';
      }
    }, opts);

    navItems.forEach((i) => {
      if (i.section) {
        const el = document.getElementById(i.section);
        if (el) observer.observe(el);
      }
    });

    return () => observer.disconnect();
  }
});

function getHref(item: any) {
  if (onHome && item.section) return `#${item.section}`;
  if (item.route) return item.route;
  if (item.section) return `/#${item.section}`;
  return '/';
}

function isItemActive(item: any) {
  if (onHome && item.section) return active === item.section;
  return false;
}
</script>

<header
  class="fixed top-0 left-0 right-0 z-100 border-b-2 border-border bg-background/95 backdrop-blur-sm transition-all duration-300"
>
  <div
    class="container-custom h-16 md:h-18 lg:h-20 flex items-center justify-between"
  >
    <!-- Brand -->
    <a
      href="/"
      class="text-xl md:text-2xl font-black tracking-tighter text-foreground hover:text-primary transition-colors uppercase"
    >
      Madusha<span class="text-primary">.</span>
    </a>

    <!-- Desktop Nav -->
    <nav class="hidden lg:flex items-center gap-8">
      <ul class="flex items-center gap-6 lg:gap-8">
        {#each navItems as item}
          {#if !item.homepageOnly || onHome}
            {@const href = getHref(item)}
            {@const isActive = isItemActive(item)}
            <li>
              <a
                {href}
                onclick={(e) =>
                  item.section && onHome
                    ? handleSectionNav(e, item.section)
                    : null}
                class={`relative text-xs font-bold uppercase tracking-widest transition-colors duration-200
                      ${
                        item.cta
                          ? "px-6 py-3 bg-primary text-primary-foreground hover:bg-foreground hover:text-background border-2 border-transparent hover:border-foreground"
                          : isActive
                            ? "text-primary"
                            : "text-muted-foreground hover:text-foreground"
                      }
                    `}
              >
                {item.label}
                {#if isActive && !item.cta}
                  <span
                    class="absolute -bottom-2 left-0 w-full h-0.5 bg-primary"
                  ></span>
                {/if}
              </a>
            </li>
          {/if}
        {/each}
      </ul>
      <div class="pl-8 border-l-2 border-border h-8 flex items-center">
        <ThemeToggle />
      </div>
    </nav>

    <!-- Mobile Navigation - Redesigned -->
    <div class="flex items-center gap-3 lg:hidden">
      <ThemeToggle />
      <button
        class="flex items-center justify-center w-10 h-10 border-2 border-border bg-card hover:bg-primary hover:text-primary-foreground hover:border-primary transition-all"
        onclick={() => (menuOpen = !menuOpen)}
        aria-label="Toggle menu"
      >
        {#if menuOpen}
          <svg
            width="20"
            height="20"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <line x1="18" y1="6" x2="6" y2="18"></line>
            <line x1="6" y1="6" x2="18" y2="18"></line>
          </svg>
        {:else}
          <svg
            width="20"
            height="20"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <line x1="3" y1="12" x2="21" y2="12"></line>
            <line x1="3" y1="6" x2="21" y2="6"></line>
            <line x1="3" y1="18" x2="21" y2="18"></line>
          </svg>
        {/if}
      </button>
    </div>
  </div>
</header>

<!-- Mobile Menu - Clean Slide-in Design -->
{#if menuOpen}
  <div
    class="lg:hidden fixed top-16 md:top-18 bottom-0 left-0 right-0 z-40 bg-background/98 backdrop-blur-md border-t-2 border-border"
  >
    <nav class="container-custom h-full flex flex-col py-6">
      <ul class="flex flex-col gap-2">
        {#each navItems as item}
          {#if !item.homepageOnly || onHome}
            {@const href = getHref(item)}
            {@const isActive = isItemActive(item)}
            <li>
              <a
                {href}
                onclick={(e) => {
                  if (item.section && onHome) handleSectionNav(e, item.section);
                  else menuOpen = false;
                }}
                class={`block px-4 py-3 text-base font-bold uppercase tracking-wide border-l-4 transition-all
                         ${
                           item.cta
                             ? "border-primary text-primary bg-primary/5"
                             : isActive
                               ? "border-primary text-primary bg-primary/5"
                               : "border-transparent text-muted-foreground hover:border-border hover:text-foreground hover:bg-muted/30"
                         }
                       `}
              >
                {item.label}
              </a>
            </li>
          {/if}
        {/each}
      </ul>

      <div class="mt-auto pt-6 border-t-2 border-border">
        <p
          class="text-xs font-mono text-muted-foreground uppercase tracking-wider text-center"
        >
          Navigate to any section
        </p>
      </div>
    </nav>
  </div>
{/if}

// components/shared/Navbar.tsx
"use client";

import { m } from "framer-motion";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ThemeToggle } from "./ThemeToggle";
import { cn } from "@/lib/utils";

const navItems = [
  { name: "Home", path: "#home" },
  { name: "Services", path: "#services" },
  { name: "About", path: "#about" },
  { name: "Projects", path: "#projects" },
  { name: "Blog", path: "#toparticles" },
  { name: "Contact", path: "#contact" },
];

export default function NavBar() {
  const [activePath, setActivePath] = useState("home");
  const [isFloating, setIsFloating] = useState(false);

  const scrollToView = (e: React.MouseEvent<HTMLAnchorElement>): void => {
    e.preventDefault();
    const href = e.currentTarget.getAttribute("href");
    if (!href) return;
    const element = document.querySelector(href);
    if (element instanceof HTMLElement) {
      const offsetTop = element.offsetTop - 100;
      window.scrollTo({
        top: offsetTop,
        behavior: "smooth",
      });
    }
  };

  const handleScroll = () => {
    const scrollY = window.scrollY;
    setIsFloating(scrollY > 100);

    // Detect active section
    const sections = document.querySelectorAll("section");
    let currentSection: string | null = "";

    sections.forEach((section) => {
      const sectionTop = section.offsetTop - 200;
      if (scrollY >= sectionTop) {
        currentSection = section.getAttribute("id");
      }
    });

    if (currentSection) {
      setActivePath(`#${currentSection}`);
    }
  };

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  return (
    <m.div
      className={cn(
        "z-50 mx-auto w-full transition-all duration-500 ease-in-out",
        isFloating
          ? "fixed top-4 left-1/2 max-w-fit -translate-x-1/2"
          : "sticky top-0 mb-8 max-w-full"
      )}
      layout
    >
      <div
        className={cn(
          "transition-all duration-500 ease-in-out",
          isFloating
            ? "glass-effect rounded-full px-4 py-2 shadow-lg"
            : "bg-card border-border rounded-none border-b p-2 backdrop-blur-md"
        )}
      >
        <nav
          className={cn(
            "relative flex items-center transition-all duration-500",
            isFloating
              ? "justify-center gap-1"
              : "justify-between gap-2"
          )}
        >
          {/* Logo - hide when floating */}
          <m.h3
            className={cn(
              "text-primary font-mono text-xl font-black transition-all duration-500",
              isFloating
                ? "w-0 overflow-hidden opacity-0"
                : "block rounded-full px-4 py-2 opacity-100"
            )}
          >
            <Link href="/">://madusha</Link>
          </m.h3>

          {/* Navigation Items */}
          <div
            className={cn(
              "flex transition-all duration-500",
              isFloating ? "gap-1" : "gap-2"
            )}
          >
            {navItems.map((item) => {
              const isActive = item.path === activePath;
              return (
                <Link
                  key={item.path}
                  className={cn(
                    "relative rounded-full font-semibold no-underline transition-all duration-300 ease-in hover:scale-105",
                    isFloating
                      ? "px-3 py-1.5 text-sm"
                      : "hidden px-4 py-2 text-sm md:block lg:text-base",
                    isActive
                      ? "text-primary font-bold"
                      : isFloating
                      ? "text-muted-foreground hover:text-foreground"
                      : "hover:text-accent-foreground"
                  )}
                  href={item.path}
                  onClick={scrollToView}
                  onMouseOver={() => setActivePath(item.path)}
                  onMouseLeave={handleScroll}
                >
                  {/* Active indicator */}
                  {isActive && (
                    <m.div
                      className={cn(
                        "absolute rounded-full",
                        isFloating
                          ? "inset-0 bg-primary"
                          : "bottom-0 left-0 h-1 w-full bg-primary"
                      )}
                      layoutId="navbar-active"
                      transition={{
                        type: "spring",
                        bounce: 0.15,
                        stiffness: 80,
                        damping: 12,
                        duration: 0.3,
                      }}
                    />
                  )}
                  <span
                    className={cn(
                      "relative transition-all duration-300",
                      isActive && isFloating ? "z-10 text-white" : ""
                    )}
                  >
                    {item.name}
                  </span>
                </Link>
              );
            })}
          </div>

          {/* Theme Toggle - hide when floating */}
          <m.div
            className={cn(
              "transition-all duration-500",
              isFloating
                ? "w-0 overflow-hidden opacity-0"
                : "flex-end justify-end opacity-100"
            )}
          >
            <ThemeToggle />
          </m.div>
        </nav>
      </div>
    </m.div>
  );
}

// Keep BlogNavBar for backward compatibility
export function BlogNavBar() {
  return (
    <div className="border-border bg-card text-accent-foreground sticky top-0 z-50 mx-auto mb-8 flex w-full max-w-full rounded-none border-b p-2 backdrop-blur-md">
      <nav className="relative z-50 flex w-full justify-between gap-2 rounded-lg">
        <h3 className="text-primary not-sr-only block justify-start rounded-full px-4 py-2 font-mono text-xl font-black">
          <Link href="/blog">://madusha</Link>
        </h3>
        <div className="flex justify-between gap-2">
          <Link
            className="relative hidden rounded-full px-4 py-2 text-sm font-semibold no-underline duration-300 ease-in md:block lg:text-base hover:text-accent-foreground"
            href="/"
          >
            Home
          </Link>
          <Link
            className="relative hidden rounded-full px-4 py-2 text-sm font-semibold no-underline duration-300 ease-in md:block lg:text-base text-primary font-bold"
            href="/blog"
          >
            <span>Blog</span>
            <m.div
              className="bg-primary absolute bottom-0 left-0 -z-10 h-1 rounded-full w-full"
              layoutId="blog-navbar"
              transition={{
                type: "spring",
                bounce: 0.15,
                stiffness: 80,
                damping: 12,
                duration: 0.3,
              }}
            />
          </Link>
        </div>
        <ThemeToggle className="flex-end justify-end justify-items-end" />
      </nav>
    </div>
  );
}
